# Домашнее задание "Линейная алгебра. Матрицы".

## Уровень 0:


### Задание 1

 - Создайте матрицу 3 на 3, заполненную числами от 1 до 9
 - Прибавьте к ней матрицу с единицами на диагонале
 - Умножьте полученную матрицу на вектор (1, 2, 3)
 - Вычислить транспонированную матрицу $A^T$ от полученной в результате прибавления матрицы
 - Посчитайте обратную матрицу к полученной в результате прибавления матрице


In [18]:
### YOUR CODE HERE

In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.eye(3)

In [6]:
res = a+b

In [5]:
v = np.array([1,2,3])

In [11]:
res2 = res@v

In [14]:
np.transpose(res)

array([[ 2.,  4.,  7.],
       [ 2.,  6.,  8.],
       [ 3.,  6., 10.]])

In [27]:
np.linalg.inv(res)

array([[-6.00000000e+00, -2.00000000e+00,  3.00000000e+00],
       [-1.00000000e+00,  5.00000000e-01,  5.44009282e-16],
       [ 5.00000000e+00,  1.00000000e+00, -2.00000000e+00]])

## Уровень 1:

### Задание 2

Найдите собственные значения и собственные вектора матрицы:
```
m = np.array([[2, 2],
              [1, 3]])
print(m)
```



In [19]:
### YOUR CODE HERE

In [21]:
m = np.array([[2,2],[1,3]])

In [30]:
res2 = np.linalg.eig(m)

In [31]:
res2[0]

array([1., 4.])

In [34]:
res3 = np.transpose(res2[1])

In [46]:
res3[0]/0.4472136

array([-1.99999998,  0.99999999])

In [44]:
res3[1]/-0.70710678

array([1., 1.])

### Задание 3


Придумайте матрицу, у которой определитель = 1, и все элементы не равны 0.

P.S. Матрица должна быть ненулевой и размерностью не менее 2! 

In [ ]:
### YOUR CODE HERE

In [185]:
a2 = np.array([[1, 2, 1], [1, 1, 4], [-2, -3, -6]])

In [186]:
a2

array([[ 1,  2,  1],
       [ 1,  1,  4],
       [-2, -3, -6]])

In [187]:
np.linalg.det(a2)

1.0

In [215]:
# Все квадратные матрицы с определителем 1. Степень сложности O(n^4)

a3 = []

for i in range(-9,10):
    for j in range(-9,10):
        for ii in range(-9,10):
            for jj in range(-9,10):
                a = [i, j]
                b = [ii, jj]
                c = np.array([a,b])
                try:
                    if np.linalg.det(c) == 1 and 0 not in c:
                        a3.append(c)
                        break
                except:
                    pass
            
      

In [216]:
np.linalg.det(np.array([[-8, -9],[-7, -8]]))

1.0

In [214]:
a3

[array([[-8, -9],
        [-7, -8]]),
 array([[-8, -9],
        [ 1,  1]]),
 array([[-8, -7],
        [-1, -1]]),
 array([[-8, -7],
        [ 7,  6]]),
 array([[-8, -5],
        [-3, -2]]),
 array([[-8, -5],
        [ 5,  3]]),
 array([[-8, -3],
        [-5, -2]]),
 array([[-8, -3],
        [ 3,  1]]),
 array([[-8, -1],
        [-7, -1]]),
 array([[-8,  1],
        [ 7, -1]]),
 array([[-8,  3],
        [-3,  1]]),
 array([[-8,  3],
        [ 5, -2]]),
 array([[-8,  5],
        [-5,  3]]),
 array([[-8,  5],
        [ 3, -2]]),
 array([[-8,  7],
        [-7,  6]]),
 array([[-8,  7],
        [ 1, -1]]),
 array([[-8,  9],
        [-1,  1]]),
 array([[-8,  9],
        [ 7, -8]]),
 array([[-7, -8],
        [ 8,  9]]),
 array([[-7, -6],
        [-8, -7]]),
 array([[-7, -1],
        [ 8,  1]]),
 array([[-7,  1],
        [-8,  1]]),
 array([[-7,  6],
        [ 8, -7]]),
 array([[-7,  8],
        [-8,  9]]),
 array([[-5, -3],
        [-8, -5]]),
 array([[-5, -2],
        [ 8,  3]]),
 array([[-5,